/* Generated By:JavaCC: Do not edit this line. ExpressionLanguageParserConstants.java */
package com.wenyu7980.el;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionLanguageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int STRING = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\"\\\"\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"\\\"\"",
    "\";\"",
    "\"?\"",
    "\":\"",
    "\"!\"",
    "\"||\"",
    "\"&&\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
  };

}
